apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ../../base

images:
  - name: tech-challenge-users
    newName: ECR_IMAGE

secretGenerator:
  - name: tech-challenge-users-secret
    behavior: replace
    envs:
      - .env.secrets

configMapGenerator:
  - name: tech-challenge-users-config
    behavior: merge
    envs:
      - .env.host

patches:
  - target:
      kind: Deployment
      name: tech-challenge-users
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
      - op: add
        path: /spec/template/spec/containers/0/env
        value:
          - name: DD_AGENT_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP

generatorOptions:
  disableNameSuffixHash: true
