apiVersion: v1
kind: Service
metadata:
  name: tech-challenge-users-svc
spec:
  selector:
    app: tech-challenge-users
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: ClusterIP
